/**
 * Regenerates the .js companion modules that the game (and build-bundle.mjs)
 * actually import, from the canonical JSON data files that the admin tool
 * (/admin) reads and commits:
 *   src/data/techniqueCatalog.json -> src/data/techniqueCatalog.js
 *   src/data/bosses.json           -> src/data/bosses.js
 *   src/data/stages.json           -> src/data/stages.js
 *
 * Why not import the JSON directly? build-bundle.mjs concatenates plain JS
 * source files into a single classic <script> (no ES modules, so it also
 * works when index.html is opened via file://, where fetch() of local JSON
 * would be blocked by CORS). The JSON stays the single source of truth —
 * this script just keeps the .js mirrors in sync with it.
 *
 * Run this any time the JSON files change, before build-bundle.mjs. The
 * admin tool's commit flow runs it automatically as part of its own build
 * step (see /admin's server-side commit handler).
 */
import { readFile, writeFile } from 'node:fs/promises';

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'));
}

function banner(sourcePath) {
  return `// AUTO-GENERATED by scripts/sync-data.mjs from ${sourcePath}.\n// Do not hand-edit — edit the .json file (or use the /admin tool) and re-run the sync script.\n`;
}

const techniqueCatalog = await readJson('src/data/techniqueCatalog.json');
await writeFile(
  'src/data/techniqueCatalog.js',
  `${banner('techniqueCatalog.json')}export const techniqueCatalog = ${JSON.stringify(techniqueCatalog, null, 2)};\n\nexport const techniqueCatalogById = Object.freeze(\n  Object.fromEntries(techniqueCatalog.map((t) => [t.id, t]))\n);\n`,
  'utf8',
);

const bossRegistry = await readJson('src/data/bosses.json');
await writeFile(
  'src/data/bosses.js',
  `${banner('bosses.json')}export const bossRegistry = ${JSON.stringify(bossRegistry, null, 2)};\n\nexport const bossRegistryById = Object.freeze(\n  Object.fromEntries(bossRegistry.map((b) => [b.id, b]))\n);\n`,
  'utf8',
);

const stages = await readJson('src/data/stages.json');
await writeFile(
  'src/data/stages.js',
  `${banner('stages.json')}export const stages = ${JSON.stringify(stages, null, 2)};\n`,
  'utf8',
);

console.log('Synced src/data/*.json -> src/data/*.js');
